name: build
on: 
  push:
    branches-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Get all git history
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Set up Mage
        run: go run mage.go EnsureMage
      - name: Test Integration
        run: build/run-integration-tests.sh
      - name: Report Integration Test Coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage-integration.out
          flags: integration-tests
